version: '3'
services:
  db_{containerId}_test:
    container_name: db_{containerId}_test
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress-test
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - var_lib_mysql_test:/var/lib/mysql

  db_{containerId}:
    container_name: db_{containerId}
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - var_lib_mysql:/var/lib/mysql

  web_{containerId}:
    container_name: web_{containerId}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db_{containerId}
    environment:
      - WORDPRESS_DB_HOST=db_{containerId}
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - {environments}
      - {wordpressConfigExtra}
    volumes:
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ./.htaccess:/var/www/html/.htaccess
      - ./wp-config.php:/var/www/html/wp-config.php
      - var_www_html:/var/www/html
      - {volumes}

volumes:
  var_www_html:
  var_lib_mysql:
  var_lib_mysql_test:

networks:
  default:
    name: {network}
